### ISSUE TITLE
EXECUTOR_NUMBER

### ISSUE THREAD

**Issue by iaroslav-ai** [NervanaSystems/ModelZoo#1]
Clarify in descrption that variable EXECUTOR_NUMBER needs to be set in order to run test.sh

**Comment by iaroslav-ai** [comment]
Oops

**Comment by nervetumer** [comment]
The test functions are for internal testing of the model zoo and were not intended to be run by users.  Instructions for running the models are included in the readme for each model.  Please refer to those instructions for running the models.

**Comment by iaroslav-ai** [comment]
Thanks, I will read the readme carefully next time :)
